## Write a Numpy program to compute the multiplication of two given matrixes

In [1]:
import numpy as np 

In [2]:
a = np.array([[5,1,3],[4,4,6],[6,4,1]])
b = np.array([1,1,1])
print (a*b)

[[5 1 3]
 [4 4 6]
 [6 4 1]]


## Write a NumPy program to compute the determinant of a given square array

In [5]:
q = np.array([[5,1,3],[4,4,6],[6,4,1]])
w = np.array([1,1,1])
print (w*q**2)

[[25  1  9]
 [16 16 36]
 [36 16  1]]


## Write a NumPy program to compute the cross product of two given vectors

## Write a NumPy program to compute the condition number of a given matrix

In [6]:
my_matrix =[[1,2,3],[4,5,6],[7,8,9]]
my_matrix


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
x=np.array(my_matrix)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Write a NumPy program to compute the inverse of a given matrix